//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeePricingMgt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblProductPricing
    {
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime PricingDate { get; set; }
        public string Price { get; set; }
        public Nullable<int> TermID { get; set; }
        public int ProductID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> ShippingPeriodID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Bags { get; set; }
        public Nullable<int> CropID { get; set; }
        [NotMapped]
        public int CategoryID { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblShippingPeriod tblShippingPeriod { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblCrop tblCrop { get; set; }
        public virtual tblTerm tblTerm { get; set; }
    }
}
