//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeePricingMgt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTerm()
        {
            this.tblProductPricings = new HashSet<tblProductPricing>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPricing> tblProductPricings { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
